bcre/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('pages.urls', namespace='pages')),
    path('listings/', include('listings.urls', namespace='listings')),
    path('admin/', admin.site.urls),

]+ debug_toolbar_urls()+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from . import views


app_name = 'listings'
urlpatterns = [
    path('', views.index, name='listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    path('search', views.search, name='search'),  

]

pages/urls.py
from django.urls import path
from . import views
app_name = 'pages'

urlpatterns = [

    path('', views.index, name= 'index'),
    path('about', views.about, name='about'), 

] 

listings/models.py
from django.db import models
from django.utils import timezone 
from realtors.models import Realtor
from datetime import datetime

# Create your models here.
class Listing(models.Model):
    realtor = models.ForeignKey(Realtor, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    address = models.CharField(max_length=200)
    street = models.CharField(max_length=200)
    district = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    bedrooms = models.IntegerField()
    bathrooms = models.DecimalField(max_digits=2, decimal_places=1)
    clubhouse = models.IntegerField()
    sqrt = models.IntegerField()
    estate_size = models.FloatField(default=0.0)
    is_published = models.BooleanField(default=True)
    list_date=models.DateTimeField(auto_now_add=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)

    class Meta:
        ordering = ('-list_date',)
        indexes = [models.Index(fields=['list_date'])]

    def __str__(self):
        return self.title 
    
        
        
                   


    

realtors/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Realtor(models.Model):
    name = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='photo/%Y/%m/%d/')
    description = models.TextField(blank=True)
    phone = models.CharField(max_length=20) 
    email = models.CharField(max_length=50)
    is_mvp = models.BooleanField(default=False)
    hire_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.name 
    

listings/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'listings/listings.html')
def listing(request, listing_id):
    return render(request, 'listings/listing.html')
def search(request):
    return render(request, 'listings/search.html')

pages/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse

# Create your views here.
def index(request):
    pages_url = reverse('pages:index')
    return render(request,'pages/index.html')

def about(request):
    pages_url = reverse('pages:about')
    return render(request, 'pages/about.html') 

realtors/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href={% static "css/all.css" %} />
    <!-- Bootstrap -->
    <link rel="stylesheet" href={% static "css/bootstrap.css" %} />
    <!-- Custom -->
    <link rel="stylesheet" href={% static "css/style.css" %} />
    <!-- Lightbox -->
    <link rel="stylesheet" href={% static "css/lightbox.min.css" %} /> 
    <title>BC Real Estate</title>
  </head>
  <body>
    {% include "partials/_topbar.html" %}
    {% include "partials/_navbar.html" %}

    {% block content %}{% endblock %}
    {% include "partials/_footer.html" %}

    <script src={% static "js/jquery-3.3.1.min.js" %}></script>
    <script src={% static "js/bootstrap.bundle.min.js" %}></script>
    <script src={% static "js/main.js" %}></script>
    <script src={% static "js/lightbox.min.js" %}></script>
  </body>

</html>




  

templates/listings/listing.html
{% extends "base.html" %} {% block content %}
<h1>listings</h1>
{% endblock content %}

templates/listings/listings.html
{% extends "base.html" %} {% block content %}
<h1>listings</h1>
{% endblock content %}

templates/listings/search.html
{% extends "base.html" %} {% block content %}
<h1>listings</h1>
{% endblock content %}

templates/pages/about.html
{% extends "base.html" %} 
{% load static %}
{% block content %}

    
    <section id="showcase-inner" class="py-5 text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <h1 class="display-4">About BC Real Estate</h1>
            <p class="lead">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
              pariatur!
            </p>
          </div>
        </div>
      </div>
    </section>
    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
      <div class="container">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">

              <a href={% url 'pages:index' %}> <i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item active">About</li>
          </ol>
        </nav>
      </div>
    </section>
    <section id="about" class="py-4">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <h2>We Search For The Perfect Home</h2>
            <p class="lead">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
              pariatur!
            </p>

            <img src={% static 'img/about.jpg' %} alt="" />
            <p class="mt-4">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Perspiciatis esse officia repudiandae ad saepe ex, amet neque quod
              accusamus rem quia magnam magni dolorum facilis ullam minima
              perferendis? Exercitationem at quaerat commodi id libero eveniet
              harum perferendis laborum molestias quia.
            </p>
          </div>
          <div class="col-md-4">
            <div class="card">
{% comment %} fix link later {% endcomment %}
              <img
                class="card-img-top"
                src="assets/img/realtors/kyle.jpg"
                alt="Seller of the month"
              />
              <div class="card-body">
                <h5 class="card-title">Seller Of The Month</h5>
                <h6 class="text-secondary">Kyle chan</h6>
                <p class="card-text">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis
                  nesciunt amet, illo itaque similique repellat. content.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- Work -->
    <section id="work" class="bg-dark text-white text-center">
      <h2 class="display-4">We Work For You</h2>
      <h4>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem velit
        aperiam, unde aliquid at similique!
      </h4>
      <hr />
{% comment %} fix link later {% endcomment %}
      <a href="listings.html" class="btn btn-secondary text-white btn-lg"
        >View Our Featured Listings</a
      >
    </section>
    <!-- Team -->
    <section id="team" class="py-5">
      <div class="container">
        <h2 class="text-center">Our Team</h2>
        <div class="row text-center">
          <div class="col-md-4">
{% comment %} fix link later {% endcomment %}
            <img
              src="assets/img/realtors/kyle.jpg"
              alt=""
              class="rounded-circle mb-3"
            />
            <h4>Kyle Chan</h4>
            <p class="text-success">
              <i class="fas fa-award text-success mb-3"></i> Realtor
            </p>
            <hr />
            <p><i class="fas fa-phone"></i> (852)-555-5555</p>
            <p><i class="fas fa-envelope-open"></i> kyle@bcrealestate.co</p>
          </div>

          <div class="col-md-4">
{% comment %} fix link later {% endcomment %}
            <img
              src="assets/img/realtors/mark.jpg"
              alt=""
              class="rounded-circle mb-3"
            />
            <h4>Mark Lee</h4>
            <p class="text-success">Realtor</p>
            <hr />
            <p><i class="fas fa-phone"></i> (852)-444-4444</p>
            <p><i class="fas fa-envelope-open"></i> mark@bcrealestate.co</p>
          </div>

          <div class="col-md-4">
{% comment %} fix link later {% endcomment %}
            <img
              src="assets/img/realtors/jenny.jpg"
              alt=""
              class="rounded-circle mb-3"
            />
            <h4>Jenny Cheung</h4>
            <p class="text-success">Realtor</p>
            <hr />
            <p><i class="fas fa-phone"></i> (852)-333-3333</p>
            <p><i class="fas fa-envelope-open"></i> jenny@bcrealestate.co</p>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

templates/pages/index.html
{% extends "base.html" %} {% block content %}

<section id="showcase">
      <div class="container text-center">
        <div class="home-search p-5">
          <div class="overlay p-5">
            <h1 class="display-4 mb-4">Property Searching Just Got So Easy</h1>
            <p class="lead">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit.
              Recusandae quas, asperiores eveniet vel nostrum magnam voluptatum
              tempore! Consectetur, id commodi!
            </p>
            <div class="search">
{% comment %} fix link later {% endcomment %}
              <form action="search.html">
                <!-- Form Row 1 -->
                <div class="form-row">
                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Keywords</label>
                    <input
                      type="text"
                      name="keywords"
                      class="form-control"
                      placeholder="Keyword (Bathrooms, ClubHouse, etc)"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">street</label>
                    <input
                      type="text"
                      name="street"
                      class="form-control"
                      placeholder="Street"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">District</label>
                    <select name="district" class="form-control">
                      <option selected="true" disabled="disabled">
                        District (All)
                      </option>
                      <option value="IL">Islands</option>
                      <option value="KT">Kwai Tsing</option>
                      <option value="NR">North</option>
                      <option value="SK">Sai Kung</option>
                      <option value="ST">Sha Tin</option>
                      <option value="TP">Tai Po</option>
                      <option value="TW">Tsuen Wan</option>
                      <option value="TM">Tuen Mun</option>
                      <option value="YL">Yuen Long</option>
                      <option value="KC">Kowloon City</option>
                      <option value="KW">Kwun Tong</option>
                      <option value="SS">Sham Shui Po</option>
                      <option value="WT">Wong Tai Sin</option>
                      <option value="YM">Yau Tsim Mong</option>
                      <option value="CW">Central & Western</option>
                      <option value="ER">Eastern</option>
                      <option value="SR">Southern</option>
                      <option value="WC">Wan Chai</option>
                    </select>
                  </div>
                </div>
                <!-- Form Row 2 -->
                <div class="form-row">
                  <div class="col-md-6 mb-3">
                    <label class="sr-only">Bedrooms</label>
                    <select name="bedrooms" class="form-control">
                      <option selected="true" disabled="disabled">
                        Bedrooms (All)
                      </option>
                      <option value="1">1</option>
                      <option value="2">2</option>
                      <option value="3">3</option>
                      <option value="4">4</option>
                      <option value="5">5</option>
                      <option value="6">6</option>
                      <option value="7">7</option>
                      <option value="8">8</option>
                      <option value="9">9</option>
                      <option value="10">10</option>
                    </select>
                  </div>
                  <div class="col-md-6 mb-3">
                    <select name="price" class="form-control" id="type">
                      <option selected="true" disabled="disabled">
                        Max Price (Any)
                      </option>
                      <option value="1000000">$1,000,000</option>
                      <option value="2000000">$2,000,000</option>
                      <option value="3000000">$3,000,000</option>
                      <option value="4000000">$4,000,000</option>
                      <option value="5000000">$5,000,000</option>
                      <option value="6000000">$6,000,000</option>
                      <option value="7000000">$7,000,000</option>
                      <option value="8000000">$8,000,000</option>
                      <option value="9000000">$9,000,000</option>
                      <option value="10000000">$10M+</option>
                    </select>
                  </div>
                </div>
                <button class="btn btn-secondary btn-block mt-4" type="submit">
                  Submit form
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section id="listings" class="py-5">
      <div class="container">
        <h3 class="text-center mb-3">Latest Listings</h3>
        <div class="row">
          <!-- Listing 1 -->
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card listing-preview">
{% comment %} fix link later {% endcomment %}
              <img
                class="card-img-top"

                src="assets/img/homes/home-1.jpg"
                alt=""
              />

              <div class="card-img-overlay">
                <h2>
                  <span class="badge badge-secondary text-white"
                    >$4,900,000</span
                  >
                </h2>
              </div>
              <div class="card-body">
                <div class="listing-heading text-center">
                  <h4 class="text-primary">45 Prince Street</h4>
                  <p>
                    <i class="fas fa-map-marker text-secondary"></i> Yau Tsim
                    Mong
                  </p>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-th-large"></i> Sqft: 2500
                  </div>
                  <div class="col-6">
                    <i class="fas fa-dumbbell"></i> ClubHouse: 2
                  </div>
                </div>
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-bed"></i> Bedrooms: 3
                  </div>
                  <div class="col-6">
                    <i class="fas fa-bath"></i> Bathrooms: 2
                  </div>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-6"><i class="fas fa-user"></i> Kyle Chan</div>
                </div>
                <div class="row text-secondary pb-2">
                  <div class="col-6">
                    <i class="fas fa-clock"></i> 5 days ago
                  </div>
                </div>
                <hr />
{% comment %} fix link later {% endcomment %}
                <a href="listing.html" class="btn btn-primary btn-block"
                  >More Info</a
                >
              </div>
            </div>
          </div>

          <!-- Listing 2 -->
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card listing-preview">
{% comment %} fix link later {% endcomment %}
              <img
                class="card-img-top"
                src="assets/img/homes/home-2.jpg"
                alt=""
              />

              <div class="card-img-overlay">
                <h2>
                  <span class="badge badge-secondary text-white"
                    >$5,500,000</span
                  >
                </h2>
              </div>
              <div class="card-body">
                <div class="listing-heading text-center">
                  <h4 class="text-primary">Hung Hom Estate</h4>
                  <p>
                    <i class="fas fa-map-marker text-secondary"></i> Kowloon
                    City
                  </p>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-th-large"></i> Sqft: 3200
                  </div>
                  <div class="col-6">
                    <i class="fas fa-dumbbell"></i> ClubHouse: 1
                  </div>
                </div>
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-bed"></i> Bedrooms: 4
                  </div>
                  <div class="col-6">
                    <i class="fas fa-bath"></i> Bathrooms: 2.5
                  </div>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-user"></i> Mark Hudson
                  </div>
                </div>
                <div class="row text-secondary pb-2">
                  <div class="col-6">
                    <i class="fas fa-clock"></i> 5 days ago
                  </div>
                </div>
                <hr />
{% comment %} fix link later {% endcomment %}
                <a href="listing.html" class="btn btn-primary btn-block"
                  >More Info</a
                >
              </div>
            </div>
          </div>

          <!-- Listing 3 -->
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card listing-preview">
{% comment %} fix link later {% endcomment %}
              <img
                class="card-img-top"
                src="assets/img/homes/home-3.jpg"
                alt=""
              />

              <div class="card-img-overlay">
                <h2>
                  <span class="badge badge-secondary text-white"
                    >$5,800,000</span
                  >
                </h2>
              </div>
              <div class="card-body">
                <div class="listing-heading text-center">
                  <h4 class="text-primary">Mei Foo</h4>
                  <p>
                    <i class="fas fa-map-marker text-secondary"></i> Sham Shui
                    Po
                  </p>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-th-large"></i> Sqft: 3107
                  </div>
                  <div class="col-6">
                    <i class="fas fa-dumbbell"></i> ClubHouse: 0
                  </div>
                </div>
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-bed"></i> Bedrooms: 4
                  </div>
                  <div class="col-6">
                    <i class="fas fa-bath"></i> Bathrooms: 3
                  </div>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-6"><i class="fas fa-user"></i> Mark Lee</div>
                </div>
                <div class="row text-secondary pb-2">
                  <div class="col-6">
                    <i class="fas fa-clock"></i> 5 days ago
                  </div>
                </div>
                <hr />
{% comment %} fix link later {% endcomment %}
                <a href="listing.html" class="btn btn-primary btn-block"
                  >More Info</a
                >
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

 <section id="services" class="py-5 bg-secondary text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-4">
            <i class="fas fa-comment fa-4x mr-4"></i>
            <hr />
            <h3>Consulting Services</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt,
              debitis nam! Repudiandae, provident iste consequatur hic
              dignissimos ratione ea quae.
            </p>
          </div>
          <div class="col-md-4">
            <i class="fas fa-home fa-4x mr-4"></i>
            <hr />
            <h3>Propery Management</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt,
              debitis nam! Repudiandae, provident iste consequatur hic
              dignissimos ratione ea quae.
            </p>
          </div>
          <div class="col-md-4">
            <i class="fas fa-suitcase fa-4x mr-4"></i>
            <hr />
            <h3>Renting & Selling</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt,
              debitis nam! Repudiandae, provident iste consequatur hic
              dignissimos ratione ea quae.
            </p>
          </div>
        </div>
      </div>
    </section>
   
{% endblock %}

templates/partials/_footer.html
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
      Copyright &copy;
      <span class="year"></span> BC Real Estate
    </footer>

    

templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
      <div class="container">
        
        
        <a class="navbar-brand" href={% url "pages:index" %}>
            
          <img src={% static "img/logo.png" %} class="logo" alt="" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavAltMarkup"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <ul class="navbar-nav">
            <li {% if request.path == '/' %} class="nav-item active mr-3" {% else %}
            class = "nav-item mr-3" {% endif %}>
                
              <a class="nav-link" href={% url "pages:index" %}>Home</a>
              
            </li>
            <li {% if 'about' in request.path %} class= "nav-item active mr-3" {% else %}
            class = "nav-item mr-3" {% endif %} >
          
                
              <a class="nav-link" href={% url "pages:about" %}>About</a>
            </li>
            <li class="nav-item mr-3">
                {% comment %} fix link later {% endcomment %}
              <a class="nav-link" href={% url "listings:listings" %}>Featured Listings</a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-3">
                {% comment %} fix link later {% endcomment %}
              <a class="nav-link" href="register.html">
                <i class="fas fa-user-plus"></i> Register</a
              >
            </li>
            <li class="nav-item mr-3">
                {% comment %} fix link later {% endcomment %}
              <a class="nav-link" href="login.html">
                <i class="fas fa-sign-in-alt"></i>

                Login</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

templates/partials/_topbar.html
<section id="top-bar" class="p-3">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <i class="fas fa-phone"></i> (852)-555-5555
          </div>
          <div class="col-md-4">
            <i class="fas fa-envelope-open"></i> contact@bcrealestate.co
          </div>
          <div class="col-md-4">
            <div class="social text-right">
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#">
                <i class="fab fa-facebook"></i>
              </a>
              <a href="#">
                <i class="fab fa-linkedin"></i>
              </a>
              <a href="#">
                <i class="fab fa-instagram"></i>
              </a>
              <a href="#">
                <i class="fab fa-pinterest"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>